### ISSUE TITLE
Is it possible to make @Pings with this webhook?

### ISSUE THREAD

**Issue by israpps** [tsickert/discord-webhook#3]
Quite self explanatory

**Comment by tsickert** [comment]
Hey @israpps! Yes, it is possible. Discord @ messages have a plaintext syntax of `<@{user_id}>`, so just use that notation instead of the `@person` notation. 

I just added a section in the [README ](https://github.com/tsickert/discord-webhook/blob/master/README.md#faq) based on this issue that goes into a little more detail and has instructions on getting that user ID if you don't have it already.

Let me know if you have any other questions!
